name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-sample-addin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install mingw-w64
      run: sudo apt-get -y install mingw-w64
    - name: Build sample AddIn
      working-directory: ./sample_addin_rs
      run: cargo build
  
  test-macros:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install mingw-w64
      run: sudo apt-get -y install mingw-w64
    - name: Build macros
      working-directory: ./
      run: cargo test -p native_api_1c_macro